### PR TITLE
Bump recommended GHC version in the vanilla channel

### PR DESCRIPTION
**Pull request by fendor**
That should unbreak our release CI https://github.com/haskell/haskell-language-server/issues/4120

### CODE REVIEW

**Comment by fendor** [comment]
@wz1000 Could you sign these?

**Comment by hasufell** [comment]
Generally, `recommended` and `latest` are supposed to point to the same version. At least that's how it had been maintained before. If GHC devs want to deviate, I don't really mind, though.

**Comment by fendor** [comment]
I wasn't aware of that history.

Setting `recommended` to `latest` would break the nightly HLS release CI again when a new GHC release happens, but HLS hasn't caught up with it yet. Perhaps we should manually set the GHC version in the release CI job. That way, there will be no surprises.

**Comment by hasufell** [comment]
superseded by https://github.com/haskell/ghcup-metadata/commit/96270a6e47c9f1fbf35fb987838928f5ab11e136

**Pull request closed without merging**
