### PR TITLE
Metadata for GHC 9.6.4

### PR DESCRIPTION
**Pull request by wz1000**
https://gitlab.haskell.org/ghc/ghcup-ci/-/jobs/1747962

### CODE REVIEW

**Comment by wz1000** [comment]
https://github.com/haskell/ghcup-metadata/actions/runs/7458821192

**Comment by phadej** [comment]
So this updates the `ghcup-vanilla` channel, but not the default one. Will we now need for @hasufell to update the main one?

**Comment by wz1000** [comment]
yes

**Comment by hasufell** [comment]
> So this updates the `ghcup-vanilla` channel, but not the default one. Will we now need for @hasufell to update the main one?

armv7 and FreeBSD bindists will have to be built manually.

**Pull request merged**
