### PR TITLE
add cabal-install-3.12.1.0 to vanilla channel

### PR DESCRIPTION
**Pull request by geekosaur**
I've removed the signature file, since my GPG isn't cross-signed by any GHCup devs. This commit is signed, though.

### CODE REVIEW

**Comment by geekosaur** [comment]
Something went wrong somewhere, it seems to be replacing 3.10.3 instead of adding a new section, plus I'm told that my changed version tagging isn't included.

**Comment by ulysses4ever** [comment]
@hasufell can we merge this?

**Comment by hasufell** [comment]
It hasn't been tested. We need to run the bindist pipeline at least once.

That only works with branches in the main repo.

**Comment by ulysses4ever** [comment]
@hasufell that's all right. What can Cabal team do to make it happen (if anything)?

**Comment by hasufell** [comment]
@Kleidukos has access rights and cross signed keys:

https://github.com/haskell/ghcup-metadata/blob/8660660df4c45b2c5d2d0cac025abde2e097beb3/.github/workflows/sigs#L5

**Comment by Kleidukos** [comment]
On it.

**Pull request closed without merging**
