### PR TITLE
Release HLS 2.7.0.0

### PR DESCRIPTION
**Pull request by fendor**
These binaries are built against the vanilla channel.
Thus, there are also no FreeBSD binaries.

See https://github.com/haskell/haskell-language-server/pull/4095 for release details.

### CODE REVIEW

**Comment by fendor** [comment]
I am no longer supposed to update `hls-metadata.json`, right?

**Comment by fendor** [comment]
I don't know whether I can run the test jobs described here https://github.com/haskell/ghcup-metadata?tab=readme-ov-file#during-a-pull-request

**Comment by hasufell** [comment]
Your signature is not supported.

https://github.com/haskell/ghcup-metadata/blob/develop/.github/workflows/sigs

Someone in that list needs to sign

**Comment by hasufell** [comment]
> I am no longer supposed to update `hls-metadata.json`, right?

Correct

**Comment by hasufell** [comment]
> I don't know whether I can run the test jobs described here https://github.com/haskell/ghcup-metadata?tab=readme-ov-file#during-a-pull-request

You can't. Someone has to push to a branch in this repo.

**Comment by wz1000** [comment]
Closing in favour of #179

**Pull request closed without merging**
