### PR TITLE
Recommend GHC-9.4.8 and HLS-2.5.0.0

### PR DESCRIPTION
**Pull request by hasufell**

### CODE REVIEW

**Comment by hasufell** [comment]
* https://github.com/haskell/ghcup-metadata/actions/runs/7330161297
* https://github.com/haskell/ghcup-metadata/actions/runs/7330163634

**Comment by hasufell** [comment]
Any objections @mpickering @wz1000?

**Comment by wz1000** [comment]
None from me.

**Comment by wz1000** [comment]
What about the vanilla yaml?

**Comment by hasufell** [comment]
> What about the vanilla yaml?

In the vanilla yaml, recommended is always equivalent to latest.

https://github.com/haskell/ghcup-metadata/blob/7e1a50cfff66fdc4039535ea2251fd62a0521579/ghcup-vanilla-0.0.8.yaml#L5619-L5622

**Pull request merged**
