### PR TITLE
Metadata for HLS 2.3.0.0

### PR DESCRIPTION
**Pull request by wz1000**
FreeBSD CI wasn't working so those binaries aren't included

### CODE REVIEW

**Comment by wz1000** [comment]
https://github.com/haskell/ghcup-metadata/actions/runs/6349106564

**Comment by wz1000** [comment]
Sorry wrong branch: https://github.com/haskell/ghcup-metadata/actions/runs/6349125624

**Comment by wz1000** [comment]
https://github.com/haskell/ghcup-metadata/actions/runs/6349138943/job/17246839367

**Comment by hasufell** [comment]
> FreeBSD CI wasn't working so those binaries aren't included
> 

Why?

**Comment by wz1000** [comment]
> > FreeBSD CI wasn't working so those binaries aren't included
> 
> Why?

Cirrus simply wasn't picking up the jobs: https://github.com/haskell/haskell-language-server/pull/3818/checks?check_run_id=17221001135

**Comment by hasufell** [comment]
https://cirrus-ci.com/build/4985988468965376

Please put some effort into keeping FreeBSD bindists.

**Comment by wz1000** [comment]
I don't understand why the check job is failing.

**Comment by wz1000** [comment]
> https://cirrus-ci.com/build/4985988468965376
> 
> Please put some effort into keeping FreeBSD bindists.

I did, I fixed an issue on freebsd being unable to build text 2.0 specifically: https://github.com/haskell/haskell-language-server/pull/3818/commits/458ccdb55c9ea22cd5d13ec3051aaefb295321be

I have no idea about how to debug cirrus CI and don't have an account, so gave up at that point.

**Comment by wz1000** [comment]
> I don't understand why the check job is failing.

I see, the problem is `[ Error ] Tags not unique for hls: [latest]`

**Comment by wz1000** [comment]
> https://cirrus-ci.com/build/4985988468965376
> 
> Please put some effort into keeping FreeBSD bindists.

What was the problem?

**Comment by hasufell** [comment]
> > https://cirrus-ci.com/build/4985988468965376
> > 
> > Please put some effort into keeping FreeBSD bindists.
> 
> What was the problem?

I dunno. We don't have credits and it seems our job wasn't picked up immediately. 

If we use credits, it'll be faster.

**Comment by hasufell** [comment]
> I have no idea about how to debug cirrus CI

Like any other CI.

> and don't have an account, so gave up at that point.

You log in with your github OAuth.

**Comment by wz1000** [comment]
Freebsd bindists have been added

**Pull request merged**
