### PR TITLE
Add stack-2.9.3

### PR DESCRIPTION
**Pull request by hasufell**
@mpilgrem is this ready?

### CODE REVIEW

**Comment by hasufell** [comment]
Unofficial binaries here (including darwin aarch64): https://downloads.haskell.org/ghcup/unofficial-bindists/stack/2.9.3/

Pipeline: https://gitlab.haskell.org/maerwald/stack/-/pipelines/60359

**Comment by hasufell** [comment]
Bindist installation CI job: https://github.com/haskell/ghcup-metadata/actions/runs/3719731830

**Comment by mpilgrem** [comment]
@hasufell, the pause in my announcing the release of Stack 2.9.3 is related only to updating https://get.haskellstack.org (see https://github.com/commercialhaskell/get-haskellstack-org/pull/1 - I don't have commit rights for that repository). In all other respects. Stack 2.9.3 is ready. I am hoping that Stack's own build for Linux/AArch64 will be fine this time and not repeat the Stack 2.9.1 problem - see https://github.com/commercialhaskell/stack/issues/5871#issuecomment-1324046988.

**Comment by hasufell** [comment]
@bindistTest stack 2.9.3 ghcup-0.0.7.yaml

**Comment by hasufell** [comment]
@bindistTest stack 2.9.3 ghcup-0.0.7.yaml

**Comment by hasufell** [comment]
@bindistTest stack 2.9.3 ghcup-0.0.7.yaml

**Comment by hasufell** [comment]
@bindistTest stack 2.9.3 ghcup-0.0.7.yaml

**Comment by hasufell** [comment]
@bindistTest stack 2.9.3 ghcup-0.0.7.yam

**Comment by hasufell** [comment]
@bindistTest stack 2.9.3 ghcup-0.0.7.yaml

**Comment by hasufell** [comment]
@bindistTest stack 2.9.3 ghcup-0.0.7.yaml

**Comment by hasufell** [comment]
@bindistTest stack 2.9.3 ghcup-0.0.7.yaml stack-2.9.3

**Comment by hasufell** [comment]
@bindistTest stack 2.9.1 ghcup-0.0.7.yaml

**Comment by hasufell** [comment]
@bindistTest stack 2.9.3 ghcup-0.0.7.yaml stack-2.9.3

**Comment by hasufell** [comment]
@bindistTest stack 2.9.3 ghcup-0.0.7.yaml stack-2.9.3

**Comment by hasufell** [comment]
@bindistTest stack 2.9.3 ghcup-0.0.7.yaml stack-2.9.3

**Comment by hasufell** [comment]
@bindistTest stack 2.9.3 ghcup-0.0.7.yaml stack-2.9.3

**Comment by hasufell** [comment]
@bindistTest stack 2.9.3 ghcup-0.0.7.yaml stack-2.9.3

**Comment by hasufell** [comment]
@bindistTest stack 2.9.3 ghcup-0.0.7.yaml stack-2.9.3

**Comment by hasufell** [comment]
@bindistTest stack 2.9.1 ghcup-0.0.7.yaml

**Comment by hasufell** [comment]
@bindistTest stack 2.9.1 ghcup-0.0.7.yaml

**Comment by hasufell** [comment]
@bindistTest stack 2.9.1 ghcup-0.0.7.yaml stack-2.9.3

**Comment by hasufell** [comment]
@bindistTest stack 2.9.1 ghcup-0.0.7.yaml

**Comment by hasufell** [comment]
@bindistTest stack 2.9.3 ghcup-0.0.7.yaml stack-2.9.3

**Comment by hasufell** [comment]
@bindistTest stack 2.9.1 ghcup-0.0.7.yaml

**Comment by hasufell** [comment]
@bindistTestRef stack 2.9.3 ghcup-0.0.7.yaml stack-2.9.3

**Pull request closed without merging**
