### PR TITLE
Add GHC-9.6.3

### PR DESCRIPTION
**Pull request by chreekat**

### CODE REVIEW

**Comment by wz1000** [comment]
Signing will have to be done by @bgamari or me.

**Comment by wz1000** [comment]
I don't think github allows starting a workflow from a fork, can you reopen this PR after pushing to the haskell/ghcup-metadata repository please? You should have permissions now.

**Comment by chreekat** [comment]
Looks like I don't have the right rights yet.

**Comment by chreekat** [comment]
Never mind, had to accept the invitation.

**Pull request closed without merging**
