### PR TITLE
Update metadata for HLS 2.1.0.0

### PR DESCRIPTION
**Pull request by fendor**

### CODE REVIEW

**Comment by wz1000** [comment]
I've triggered a CI run for this here: https://github.com/haskell/ghcup-metadata/actions/runs/5834828076

**Comment by hasufell** [comment]
@wz1000 your gpg key is not cross-signed with mine. The only one documented and cross signed is bens: https://www.haskell.org/ghcup/guide/#gpg-verification

So either Ben has to sign the files or we have to set up your key as well.

**Comment by hasufell** [comment]
Not doing this properly can break e.g. docker image builds.

**Comment by wz1000** [comment]
@hasufell sure, Ben and I did make sure that we cross signed each others keys yesterday. I've signed your key, I think you can sign mine (`88B57FCF7DB53B4DB3BFA4B1588764FBE22D19C4`).

**Pull request merged**
