### PR TITLE
Added Mageia

### PR DESCRIPTION
**Pull request by Umeaboy**
Signed-off-by: Kristoffer Grundström <lovaren@gmail.com>

### CODE REVIEW

**Comment by hasufell** [comment]
It appears there's no such image as `mageia:9`?

**Comment by Umeaboy** [comment]
That's what I'm trying to change. Suggestion? :)

**Comment by hasufell** [comment]
https://hub.docker.com/_/mageia

**Comment by Umeaboy** [comment]
It should work now.

**Comment by Umeaboy** [comment]
Seems like it passed OK. Close this now?

**Comment by hasufell** [comment]
It didn't run the bindist job. The CI is a bit complicated.

**Comment by Umeaboy** [comment]
Could that be due to the deprecation warnings? They should be fixed nontheless.

What's my next step?

**Comment by hasufell** [comment]
Your code doesn't work: https://github.com/haskell/ghcup-metadata/actions/runs/3867382112/jobs/6592120151#step:3:25

The dependencies don't exist.

**Comment by Umeaboy** [comment]
OK to merge now? :)

**Pull request closed without merging**
