### PR TITLE
Add metadata for 9.12.1-alpha1

### PR DESCRIPTION
**Pull request by wz1000**

### CODE REVIEW

**Comment by hasufell** [comment]
Do you have an idea why debian unstable picks deb9 bindist?

https://github.com/haskell/ghcup-metadata/actions/runs/11365897332/job/31615067639

**Comment by wz1000** [comment]
nope

**Comment by hasufell** [comment]
💩

**Review by hasufell — CHANGES_REQUESTED** [review]
Fix debian unstable support.

**Comment by wz1000** [comment]
@hasufell should be fixed now, I use the deb11 job for 'unknown_version' debian, which is what ghc metadata generates, I messed up while replacing identifier names. This shouldn't happen again once https://gitlab.haskell.org/ghc/ghc/-/merge_requests/13448 lands.

However, it seems like a bug to me that debian unstable gets matched with unknown version.

**Comment by hasufell** [comment]
> However, it seems like a bug to me that debian unstable gets matched with unknown version.

Debian unstable has no version information in `/etc/os-release`, so there's no other way.

**Pull request merged**
