### PR TITLE
Added Mageia to platform

### PR DESCRIPTION
**Pull request by Umeaboy**
Signed-off-by: Kristoffer Grundström <lovaren@gmail.com>

### CODE REVIEW

**Review by hasufell — COMMENTED** [review]
This doesn't work. Mageia would first have to be added to ghcup itself. It's a type, not a string.

**Comment by Umeaboy** [comment]
What's next to do?


8 jan. 2023 15:20 av ***@***.***:

**Comment by hasufell** [comment]
I don't really understand what you're trying to do.

**Comment by Umeaboy** [comment]
> I don't really understand what you're trying to do.

To add Mageia to the Bindist installation so that ghcup will install the right version for Mageia.

**Comment by hasufell** [comment]
What is the right bindist for Mageia?

**Comment by Umeaboy** [comment]
> What is the right bindist for Mageia?

linux-mageia:9

The infrastructure for Mageia 9 is done, but it's still in Alpha1 state.

**Comment by hasufell** [comment]
I'm asking which is the right GHC bindist for Mageia. Does ghcup not work there? What is the issue you're trying to solve?

**Comment by Umeaboy** [comment]
It works, but I can't get rpmbuild to build ghc from source even though I've added ghc to $PATH. I also need ghc-devel and a couple of other dependencies as well, but I don't know how to get the installed as well. Mageia doesn't have ghc. Mandriva (which Mageia forked from) had ghc.

How do I proceed?

8 jan. 2023 15:55 av ***@***.***:

**Pull request closed without merging**
