### PR TITLE
HLS 2.9.0.0

### PR DESCRIPTION
**Pull request by wz1000**

### CODE REVIEW

**Comment by wz1000** [comment]
https://github.com/haskell/ghcup-metadata/actions/runs/9560525055

**Comment by wz1000** [comment]
https://github.com/haskell/ghcup-metadata/actions/runs/9563931646

**Comment by wz1000** [comment]
https://github.com/haskell/ghcup-metadata/actions/runs/9564200136

**Comment by fendor** [comment]
Heyo!

So, this PR can't succeed as the CI runs `HLS` on the `bytestring-0.11` codebase as a sanity check to make sure the binaries aren't completely busted from the start.

However, GHC 9.10 can't compile `bytestring-0.11`. Upgrading to `bytestring-0.12` doesn't work, because it can't be compiled with GHC 9.2 on aarch systems.

I don't understand the debian 12 error, though.

**Comment by hasufell** [comment]
Using newer bytestring-0.11 should work. 

Note that I don't mind whether CI passes or not for vanilla channel.

**Comment by hasufell** [comment]
Please don't merge via github interface. 

Merge locally into develop. Then push to develop.

Then `git push upstream develop:master`.

**Review by hasufell — APPROVED** [review]

**Comment by hasufell** [comment]
> @hasufell I don't have permissions to push to develop or master.

Can you try again?

**Comment by dfordivam** [comment]
> or what it is worth, we changed the tests to run on `text:Date.Text` in the HLS repo.

well text has bytestring as a dep, so my intuition is it will not be any better than using bytestring, in the long run.

**Pull request closed without merging**
