### PR TITLE
Fix duplicated cabal-3620-32 anchor

### PR DESCRIPTION
**Pull request by mpickering**

### CODE REVIEW

**Comment by hasufell** [comment]
Any idea how we can test for this?

**Comment by mpickering** [comment]
@hasufell I found the problem when I tried to read the file in a python script using `yaml.safe_load`.

Do you have an opinion about automatically formatting the .yaml file? It would make it easier to modify programmatically if the output was run through a formatter (any will do).

**Comment by hasufell** [comment]
The initial file was generated via aeson-yaml pretty printer afair, so it should be formatted. 

The problem is that the Haskell formatter expands the anchors afair.

**Comment by hasufell** [comment]
@mpickering basically... if you find a pretty printer that can preserve yaml anchors... let me know

**Pull request merged**
