### PR TITLE
Add GHC 9.4.1

### PR DESCRIPTION
**Pull request by amesgen**
- Alpine i386 is missing
 - FreeBSD is missing

### CODE REVIEW

**Comment by hasufell** [comment]
darwin bindist is broken and needs to be fixed https://discourse.haskell.org/t/ghc-9-4-1-is-now-available/4901/6

**Comment by amesgen** [comment]
Should I close this PR and wait for GHC 9.4.2, or is someone producing patched darwin bindists?

**Comment by hasufell** [comment]
> is someone producing patched darwin bindists?

Yeah, me.

**Comment by amesgen** [comment]
Hmm, apparently, this does not work on Ubuntu 20.04 (via `haskell/actions/setup`) as glibc is too new (the fedora33 bindist requires `GLIBC_2.32` but Ubuntu 20.04 only has 2.31). I should have tested this, sorry. I can take a look at this later today.

**Comment by RyanGlScott** [comment]
See https://gitlab.haskell.org/haskell/ghcup-hs/-/issues/403.

**Comment by amesgen** [comment]
Ok, both the Debian 10 and 11 bindist install successfully. Will create a PR to swap that out.

**Comment by hasufell** [comment]
This PR is also missing the centos bindists, so doesn't work on e.g. red hat.

**Comment by amesgen** [comment]
> This PR is also missing the centos bindists, so doesn't work on e.g. red hat.

Or at least, the YAML anchor was missing: 86c7f4374a59a4dfe76ebdebd506d8305f752488. I wonder whether sth similar would be necessary for other RHEL forks.

If there is a container image for it, we could at it do the bindist CI, but I personally have zero knowledge/context in this area, so I am not going ahead here.

**Comment by hasufell** [comment]
> > This PR is also missing the centos bindists, so doesn't work on e.g. red hat.
> 
> Or at least, the YAML anchor was missing: 86c7f4374a59a4dfe76ebdebd506d8305f752488. I wonder whether sth similar would be necessary for other RHEL forks.
> 
> If there is a container image for it, we could at it do the bindist CI, but I personally have zero knowledge/context in this area, so I am not going ahead here.

I'm using red hat myself atm

**Pull request merged**
