### PR TITLE
Vanilla bindists for HLS 2.9.0.1

### PR DESCRIPTION
**Pull request by wz1000**

### CODE REVIEW

**Comment by wz1000** [comment]
https://github.com/haskell/ghcup-metadata/actions/runs/9790875527

**Review by hasufell — APPROVED** [review]

**Comment by hasufell** [comment]
```
gpg: assuming signed data in 'ghcup-vanilla-0.0.7.yaml'
gpg: Signature made Thu Jul  4 09:03:56 2024 UTC
gpg:                using RSA key 88B57FCF7DB53B4DB3BFA4B1588764FBE22D19C4
gpg: BAD signature from "Zubin Duggal (GHC signing key) <zubin@well-typed.com>" [ultimate]
```

**Comment by wz1000** [comment]
I'm not sure what happened, do you need me to resign?

**Comment by hasufell** [comment]
> I'm not sure what happened, do you need me to resign?

I will do that, but please ensure the signature test passes: https://github.com/haskell/ghcup-metadata/actions/runs/9790875527/job/27033436873#step:4:75

**Comment by wz1000** [comment]
OK, I will pay close attention to this job in the future.

**Pull request closed without merging**
